name: Build and Deploy
on: push
permissions: 
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        working-directory: ${{env.working-directory}}
        run: |
          npm install
          npm run test
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./dist # The folder the action should deploy.